services:
  - type: web
    name: bingx-lightning-executor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent --workers 1 --threads 100 --timeout 30 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: BINGX_API_KEY
        sync: false
      - key: BINGX_SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
