services:
  - type: web
    name: bingx-lightning-executor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1 --log-level error
    envVars:
      - key: BINGX_API_KEY
        sync: false
      - key: BINGX_SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
